### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by yupthatguy** [tuberry/dict-cedict#1]
$ sudo make install
python ./cedicts.py ./cedict_1_0_ts_utf-8_mdbg.txt cedict.txt
  File "./cedicts.py", line 14
SyntaxError: Non-ASCII character '\xe2' in file ./cedicts.py on line 14, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
make: *** [Makefile:13: cedict.txt] Error 1

**Comment by tuberry** [comment]
Could be better to `make` before `sudo make install`.
